### ISSUE TITLE
Potential search algorithm improvements

### ISSUE THREAD

**Issue by Gama11** [SlavaRa/fd-quicknavigate-plugin#19]
I'm not sure how exactly it works currently, but from the way it behaves it seems like it's more or less a simple `.contains(searchString)` check. This creates some issues:

#### Exact matches should be prioritized:

![](http://i.imgur.com/IQupjAF.png)

In this case, I'd expect `FlxTile` to be the top entry, since it matches the search string *exactly* while `FlxTilemap` only *contains* the search string.

#### Matches that start with the search string should be prioritized:

![](http://i.imgur.com/r5sYSXS.png)

The order here should probably be `drawDebug()`, `drawDebugOnCamera()` and `ignoreDrawDebug`. Quick Outline currently just displays them in the order in which they appear in the class.

#### Function parameters should have a low priority:

...or maybe not be taken into account at all - I only search for function names. Either way, it seems like a match in the function name should take priority:

![](http://i.imgur.com/LXcbbEG.png)

`loadMap()` has a parameter called `DrawIndex`, which is probably why it appears in the list, but considering the other matches all have `draw` in their name, `loadMap()` should be on the bottom.

**Comment by SlavaRa** [comment]
Fixed.
https://github.com/SlavaRa/fd-quicknavigate-plugin/blob/master/QuickNavigate/Bin/Release/QuickNavigate.dll?raw=true

**Comment by Gama11** [comment]
Works a lot better now, thanks! :)
