### ISSUE TITLE
FD5 ui themes compatibilty

### ISSUE THREAD

**Issue by JeriXNet** [SlavaRa/fd-quicknavigate-plugin#22]
I'm using VsDark ui theme and Obsidian syntax theme.
"Type Explorer" looks ok:
![2015-05-09_232854](https://cloud.githubusercontent.com/assets/7815518/7551919/917be4ce-f6a3-11e4-9eeb-07a7b0852b3b.jpg)
"Open Resource" too:
![2015-05-09_233339](https://cloud.githubusercontent.com/assets/7815518/7551929/fa4b63c6-f6a3-11e4-83b5-336c467ab13c.jpg)
But "Quick Outline" is broken :(
![2015-05-09_232959](https://cloud.githubusercontent.com/assets/7815518/7551921/99a8ba64-f6a3-11e4-8d8a-13b48ad51e19.jpg)

**Comment by SlavaRa** [comment]
oh sorry, wip

**Comment by SlavaRa** [comment]
@JeriXNet release build will be tomorrow, thx for report ;)

**Comment by SlavaRa** [comment]
@JeriXNet https://github.com/SlavaRa/fd-quicknavigate-plugin/blob/master/QuickNavigate/Bin/Release/QuickNavigate.dll?raw=true

**Comment by JeriXNet** [comment]
yeah! thanks for fixing
