### ISSUE TITLE
"override" should be Ctrl-Clickable

### ISSUE THREAD

**Issue by Gama11** [SlavaRa/fd-quicknavigate-plugin#23]
See https://github.com/fdorg/flashdevelop/issues/718#issuecomment-106069463.

**Comment by SlavaRa** [comment]
Ok, WIP

**Comment by SlavaRa** [comment]
Complete: https://github.com/SlavaRa/fd-quicknavigate-plugin/raw/master/QuickNavigate/fdz/QuickNavigate-2.5-rc3.fdz

**Comment by Gama11** [comment]
You're awesome! :+1: 

Any reason that navigation by ctrl-click is disabled by default btw?

**Comment by canab** [comment]
The default state of this setting was changed to "Disabled" after some users have reported that this functionality is conflicted with text selection operations (performed by mouse and ctrl key).

**Comment by Gama11** [comment]
For example?

**Comment by canab** [comment]
http://www.flashdevelop.org/community/viewtopic.php?f=4&t=5961

**Comment by Gama11** [comment]
I see. I haven't really been able to reproduce that, you'd have to to the two actions _extremely_ quickly after each other. Maybe it used to be a bigger problem and @SlavaRa made some improvements to it?

I don't think this is a good enough reason to have the option disabled by default, but that's just my personal opinion since I use Ctrl+Click Navigation a lot and haven't run into that issue.
