### ISSUE TITLE
Project Explorer

### ISSUE THREAD

**Issue by Gama11** [SlavaRa/fd-quicknavigate-plugin#33]
Managing a ton of `.hxproj` files is a bit of a pain (flixel-demos alone has like 70 - switching between them is not fast at all). It would be amazing if there was a "Type Explorer for project files".

Searching the entire file system for project files is probably not practical. Maybe a combination of the recent projects list and an option to provide paths where to look for project files (the location of flixel-demos in my case) would work.

**Comment by SlavaRa** [comment]
Yes, it's a good idea.
I'll try to make this functionality in the next week. I will write to you when it's ready :)

**Comment by Gama11** [comment]
Awesome, thanks!

**Comment by SlavaRa** [comment]
)
